### ISSUE TITLE
Encoder returns empty array

### ISSUE THREAD

**Issue by za3k** [tomerfiliba/reedsolomon#34]
This code:

```
import reedsolo
reedsolo.RSCodec(300).encode(b'a')
```

Returns `bytearray(b'')` on my computer. Adjusting the number down causes it to return something.

**Comment by za3k** [comment]
Oh also, in case it's an issue with potential string lengths, `reedsolo.RSCodec(300, c_exp=12).encode(b'a')` instead outputs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/reedsolo.py", line 893, in encode
    enc.extend(rs_encode_msg(chunk, self.nsym, fcr=self.fcr, generator=self.generator, gen=self.gen[nsym]))
  File "/usr/lib/python3.9/site-packages/reedsolo.py", line 514, in rs_encode_msg
    msg_in = _bytearray(msg_in)
  File "/usr/lib/python3.9/site-packages/reedsolo.py", line 279, in _bytearray
    return array("i", obj)
ValueError: bytes length not a multiple of item size
```

**Comment by za3k** [comment]
Thanks for adding an error
